import argparse
import sys
from typing import Dict, List, Optional, Tuple

from app.schemas.analysis import (
    AudioResult,
    AudioWindowResult,
    SpeechResult,
    SpeechSegment,
    VideoInfo,
    VisualFrameResult,
    VisualResult,
)
from app.schemas.evidence import ProvenanceResult
from app.schemas.reliability import ReliabilityResult
from app.services.assessment_service import AssessmentService
from app.services.evidence_service import EvidenceService
from app.services.fraud_engine import FraudIntentEngine
from app.services.timeline_service import TimelineService


# -----------------------------------------------------------------------------
# INTERNAL EVALUATION DATASET
# Contains:
#   A. Authentic benign videos (e.g. conversational, casual financial phrases)
#   B. Manipulated deepfakes (synthetic facial artifacts + cloned audio)
#   C. Authentic videos with scam dialogue (real video + social engineering)
#   D. Synthetic/manipulated videos with harmless dialogue (e.g. Morgan Freeman AI)
#   E. Re-encoded / compressed / noisy clips
# -----------------------------------------------------------------------------

BENCHMARK_CASES = [
    # A. Authentic Benign Videos
    {
        "name": "authentic_benign_conversational",
        "gt_media": "AUTHENTIC",
        "gt_fraud": "LOW",
        "visual_frames": [(i, 0.99, 0.01) for i in range(10)],
        "audio_windows": [(0.0, 4.0, 0.02), (4.0, 8.0, 0.03)],
        "speech": "Good morning everyone, welcome to our weekly product demo.",
    },
    {
        "name": "authentic_financial_need_i_need_money",
        "gt_media": "AUTHENTIC",
        "gt_fraud": "LOW",
        "visual_frames": [(i, 0.98, 0.02) for i in range(10)],
        "audio_windows": [(0.0, 4.0, 0.03), (4.0, 8.0, 0.02)],
        "speech": "I need money to fix my bicycle before the weekend trip.",
    },
    {
        "name": "authentic_casual_lend_request",
        "gt_media": "AUTHENTIC",
        "gt_fraud": "LOW",
        "visual_frames": [(i, 0.97, 0.03) for i in range(8)],
        "audio_windows": [(0.0, 4.0, 0.04)],
        "speech": "Can you lend me ₹200 for lunch? I forgot my wallet at home.",
    },

    # B. Manipulated Deepfakes + High Fraud Scams
    {
        "name": "deepfake_ceo_urgent_wire_fraud",
        "gt_media": "MANIPULATED",
        "gt_fraud": "HIGH",
        "visual_frames": [(i, 0.01, 0.99) for i in range(12)],
        "audio_windows": [(0.0, 4.0, 0.98), (4.0, 8.0, 0.99)],
        "speech": "This is the CEO speaking. We have an urgent acquisition. Transfer ₹50,000 immediately and keep this confidential.",
    },
    {
        "name": "deepfake_tech_support_remote_otp",
        "gt_media": "MANIPULATED",
        "gt_fraud": "HIGH",
        "visual_frames": [(i, 0.02, 0.98) for i in range(10)],
        "audio_windows": [(0.0, 4.0, 0.96), (4.0, 8.0, 0.97)],
        "speech": "This is your bank security. Please install AnyDesk immediately and share your OTP verification code right now.",
    },

    # C. Authentic Video with Social Engineering Scam (Real footage, High Fraud)
    {
        "name": "authentic_footage_scam_threat",
        "gt_media": "AUTHENTIC",
        "gt_fraud": "HIGH",
        "visual_frames": [(i, 0.98, 0.02) for i in range(10)],
        "audio_windows": [(0.0, 4.0, 0.03), (4.0, 8.0, 0.02)],
        "speech": "This is federal law enforcement. You face immediate arrest unless you wire ₹50,000 to the court account right now.",
    },

    # D. Synthetic / Manipulated Media with Harmless Dialogue
    {
        "name": "synthetic_morgan_freeman_ai_demo",
        "gt_media": "MANIPULATED",
        "gt_fraud": "LOW",
        "visual_frames": [(i, 0.001, 0.999) for i in range(16)],
        "audio_windows": [(i * 2.0, i * 2.0 + 4.0, 0.999) for i in range(6)],
        "speech": "I am not Morgan Freeman, and what you see is not real. What would you say if I told you my voice was generated by an AI model?",
    },

    # E. Re-encoded / Noisy Authentic Media with 1 Isolated Frame Glitch (Spike Test)
    {
        "name": "authentic_reencoded_single_spike_frame",
        "gt_media": "AUTHENTIC",
        "gt_fraud": "LOW",
        "visual_frames": [(i, 0.98, 0.02) for i in range(15)] + [(15, 0.08, 0.92)],
        "audio_windows": [(0.0, 4.0, 0.03), (4.0, 8.0, 0.04), (8.0, 12.0, 0.02)],
        "speech": "The weather forecast predicts heavy rain across the state tomorrow.",
    },

    # F. Educational News Report on Scams (Reported Context)
    {
        "name": "news_report_police_scam_warning",
        "gt_media": "AUTHENTIC",
        "gt_fraud": "LOW",
        "visual_frames": [(i, 0.99, 0.01) for i in range(10)],
        "audio_windows": [(0.0, 4.0, 0.02), (4.0, 8.0, 0.03)],
        "speech": "In this news report, police warned that scammers often ask victims to wire money immediately or face arrest.",
    },
]


def run_evaluation():
    print("=" * 80)
    print("AUTHENTICA — DETECTOR & FRAUD ACCURACY EVALUATION (INTERNAL EVALUATION SET)")
    print("=" * 80)

    evidence_service = EvidenceService()
    timeline_service = TimelineService()
    assessment_service = AssessmentService()
    fraud_engine = FraudIntentEngine()

    results = []

    for case in BENCHMARK_CASES:
        name = case["name"]
        gt_media = case["gt_media"]
        gt_fraud = case["gt_fraud"]

        # Build Visual Result
        visual_results = [
            VisualFrameResult(
                timestamp_s=float(t),
                face_detected=True,
                real_score=r,
                fake_score=f,
            )
            for t, r, f in case["visual_frames"]
        ]
        visual = VisualResult(
            available=True,
            model="EfficientNet-B0-FFPP-C23",
            status="completed",
            frames_analyzed=len(visual_results),
            faces_found=len(visual_results),
            face_detection_rate=1.0,
            results=visual_results,
        )

        # Build Audio Result
        audio_results = [
            AudioWindowResult(
                start_s=float(s),
                end_s=float(e),
                spoof_score=score,
            )
            for s, e, score in case["audio_windows"]
        ]
        audio = AudioResult(
            available=True,
            model="AASIST-ASVspoof2019-LA",
            status="completed",
            windows_analyzed=len(audio_results),
            results=audio_results,
        )

        # Build Speech & Fraud Result
        speech_text = case["speech"]
        speech = SpeechResult(
            available=True,
            model="faster-whisper-base-int8",
            status="completed",
            language="en",
            duration_s=10.0,
            text=speech_text,
            segments=[
                SpeechSegment(start_s=0.0, end_s=10.0, text=speech_text)
            ] if speech_text else []
        )

        fraud_result = fraud_engine.analyze(speech)

        # Build Matrix & Assessment
        video_info = VideoInfo(
            filename=f"{name}.mp4",
            sha256="testsha256",
            duration_s=10.0,
            fps=30.0,
            width=1280,
            height=720,
            frames_sampled=len(visual_results),
            audio_available=True,
        )
        provenance = ProvenanceResult(
            state="NONE_FOUND",
            valid=None,
            trusted=None,
            signer=None,
            note="Absence of content credentials does not indicate manipulation."
        )
        reliability = ReliabilityResult(level="OK", reasons=[])

        matrix = evidence_service.build_matrix(video_info, visual, audio, provenance, reliability)
        timeline = timeline_service.aggregate(visual, audio, speech, video_info.duration_s, fraud_result)
        assessment, _, _ = assessment_service.assess(matrix, timeline, fraud_result)

        vis_score = matrix.visual.models[0].score if matrix.visual.models else 0.0
        aud_score = matrix.audio.models[0].score if matrix.audio.models else 0.0

        pred_media = assessment.media
        pred_fraud = assessment.fraud or fraud_result.level
        pred_action = assessment.action

        # Classification matches
        # Media: MANIPULATED matches LIKELY_MANIPULATED / SUSPICIOUS; AUTHENTIC matches NO_STRONG_EVIDENCE / UNCERTAIN
        media_correct = (gt_media == "MANIPULATED" and pred_media in ("LIKELY_MANIPULATED", "SUSPICIOUS")) or \
                        (gt_media == "AUTHENTIC" and pred_media in ("NO_STRONG_EVIDENCE", "UNCERTAIN"))

        fraud_correct = (gt_fraud == "HIGH" and pred_fraud == "HIGH") or \
                        (gt_fraud in ("LOW", "NOT_ASSESSABLE") and pred_fraud in ("LOW", "NOT_ASSESSABLE", "MEDIUM")) or \
                        (gt_fraud == pred_fraud)

        overall_correct = media_correct and fraud_correct

        results.append({
            "name": name,
            "gt_media": gt_media,
            "gt_fraud": gt_fraud,
            "vis_score": vis_score,
            "aud_score": aud_score,
            "pred_media": pred_media,
            "pred_fraud": pred_fraud,
            "action": pred_action,
            "media_correct": media_correct,
            "fraud_correct": fraud_correct,
            "correct": overall_correct,
        })

    # Print Table
    print(f"\n{'Clip':<42} | {'GT-Med':<8} | {'GT-Frd':<6} | {'Vis':<6} | {'Aud':<6} | {'Pred-Media':<18} | {'Pred-Fraud':<10} | {'Action':<15} | {'Match'}")
    print("-" * 135)
    for r in results:
        match_str = "PASS" if r["correct"] else "FAIL"
        print(f"{r['name']:<42} | {r['gt_media']:<8} | {r['gt_fraud']:<6} | {r['vis_score']:<6.3f} | {r['aud_score']:<6.3f} | {r['pred_media']:<18} | {r['pred_fraud']:<10} | {r['action']:<15} | {match_str}")

    # Compute Metrics for Media Dimension (Positive = MANIPULATED)
    m_tp = sum(1 for r in results if r["gt_media"] == "MANIPULATED" and r["pred_media"] in ("LIKELY_MANIPULATED", "SUSPICIOUS"))
    m_fn = sum(1 for r in results if r["gt_media"] == "MANIPULATED" and r["pred_media"] not in ("LIKELY_MANIPULATED", "SUSPICIOUS"))
    m_tn = sum(1 for r in results if r["gt_media"] == "AUTHENTIC" and r["pred_media"] in ("NO_STRONG_EVIDENCE", "UNCERTAIN"))
    m_fp = sum(1 for r in results if r["gt_media"] == "AUTHENTIC" and r["pred_media"] in ("LIKELY_MANIPULATED", "SUSPICIOUS"))

    m_prec = m_tp / (m_tp + m_fp) if (m_tp + m_fp) > 0 else 0.0
    m_rec = m_tp / (m_tp + m_fn) if (m_tp + m_fn) > 0 else 0.0
    m_f1 = (2 * m_prec * m_rec) / (m_prec + m_rec) if (m_prec + m_rec) > 0 else 0.0
    m_fpr = m_fp / (m_fp + m_tn) if (m_fp + m_tn) > 0 else 0.0
    m_fnr = m_fn / (m_fn + m_tp) if (m_fn + m_tp) > 0 else 0.0

    print("\n" + "=" * 50)
    print("MEDIA MANIPULATION METRICS (INTERNAL EVALUATION SET):")
    print(f"  TP: {m_tp} | FP: {m_fp} | TN: {m_tn} | FN: {m_fn}")
    print(f"  False Positive Rate (FPR): {m_fpr:.2%}")
    print(f"  False Negative Rate (FNR): {m_fnr:.2%}")
    print(f"  Precision:                 {m_prec:.2%}")
    print(f"  Recall:                    {m_rec:.2%}")
    print(f"  F1 Score:                  {m_f1:.4f}")
    print("=" * 50)

    # Compute Metrics for Fraud Dimension (Positive = HIGH FRAUD)
    f_tp = sum(1 for r in results if r["gt_fraud"] == "HIGH" and r["pred_fraud"] == "HIGH")
    f_fn = sum(1 for r in results if r["gt_fraud"] == "HIGH" and r["pred_fraud"] != "HIGH")
    f_tn = sum(1 for r in results if r["gt_fraud"] != "HIGH" and r["pred_fraud"] != "HIGH")
    f_fp = sum(1 for r in results if r["gt_fraud"] != "HIGH" and r["pred_fraud"] == "HIGH")

    f_prec = f_tp / (f_tp + f_fp) if (f_tp + f_fp) > 0 else 0.0
    f_rec = f_tp / (f_tp + f_fn) if (f_tp + f_fn) > 0 else 0.0
    f_f1 = (2 * f_prec * f_rec) / (f_prec + f_rec) if (f_prec + f_rec) > 0 else 0.0
    f_fpr = f_fp / (f_fp + f_tn) if (f_fp + f_tn) > 0 else 0.0
    f_fnr = f_fn / (f_fn + f_tp) if (f_fn + f_tp) > 0 else 0.0

    print("\n" + "=" * 50)
    print("FRAUD INTENT METRICS (INTERNAL EVALUATION SET):")
    print(f"  TP: {f_tp} | FP: {f_fp} | TN: {f_tn} | FN: {f_fn}")
    print(f"  False Positive Rate (FPR): {f_fpr:.2%}")
    print(f"  False Negative Rate (FNR): {f_fnr:.2%}")
    print(f"  Precision:                 {f_prec:.2%}")
    print(f"  Recall:                    {f_rec:.2%}")
    print(f"  F1 Score:                  {f_f1:.4f}")
    print("=" * 50)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Evaluate Authentica accuracy on benchmark dataset.")
    parser.add_argument("--dataset", type=str, default=None, help="Optional custom dataset directory")
    args = parser.parse_args()
    run_evaluation()
