import pytest
from app.schemas.analysis import SpeechResult, SpeechSegment
from app.services.fraud_engine import FraudIntentEngine


@pytest.fixture
def fraud_engine():
    return FraudIntentEngine()


def test_1_high_fraud_ceo_scam(fraud_engine):
    """
    Test Case 1: High-risk CEO wire scam with urgency, secrecy, and payment request.
    """
    segments = [
        SpeechSegment(
            start_s=0.0,
            end_s=3.0,
            text="This is the CEO speaking. We have an urgent acquisition deal.",
        ),
        SpeechSegment(
            start_s=3.0,
            end_s=6.0,
            text="Transfer funds immediately to the new account number and keep this strictly confidential.",
        ),
    ]
    speech = SpeechResult(
        available=True,
        model="faster-whisper-base-int8",
        status="completed",
        language="en",
        duration_s=6.0,
        text="This is the CEO speaking. We have an urgent acquisition deal. Transfer funds immediately to the new account number and keep this strictly confidential.",
        segments=segments,
    )

    result = fraud_engine.analyze(speech)
    assert result.level == "HIGH"
    assert any(cat.category == "AUTHORITY" for cat in result.categories)
    assert any(cat.category == "URGENCY" for cat in result.categories)
    assert any(cat.category == "SECRECY" for cat in result.categories)
    assert any(cat.category == "PAYMENT_CREDENTIAL" for cat in result.categories)
    assert any(act.action == "TRANSFER_MONEY" for act in result.requested_actions)
    assert not result.news_context_downgrade


def test_2_subjective_financial_need_i_need_money(fraud_engine):
    """
    Test Case 2: Subjective statement 'I need money' must NOT trigger PAYMENT_CREDENTIAL or action.
    """
    segments = [
        SpeechSegment(
            start_s=0.0,
            end_s=3.0,
            text="I need money to pay my rent this month.",
        ),
    ]
    speech = SpeechResult(
        available=True,
        model="faster-whisper-base-int8",
        status="completed",
        language="en",
        duration_s=3.0,
        text="I need money to pay my rent this month.",
        segments=segments,
    )

    result = fraud_engine.analyze(speech)
    assert result.level == "LOW"
    assert len(result.requested_actions) == 0
    assert not any(cat.category == "PAYMENT_CREDENTIAL" for cat in result.categories)


def test_3_harmless_ai_media_morgan_freeman(fraud_engine):
    """
    Test Case 3: Benign speech (Morgan Freeman AI clip).
    """
    segments = [
        SpeechSegment(
            start_s=0.0,
            end_s=4.0,
            text="I am not Morgan Freeman, and what you see is not real.",
        ),
        SpeechSegment(
            start_s=4.0,
            end_s=8.0,
            text="What would you say if I told you that my voice was generated by an AI model?",
        ),
    ]
    speech = SpeechResult(
        available=True,
        model="faster-whisper-base-int8",
        status="completed",
        language="en",
        duration_s=8.0,
        text="I am not Morgan Freeman, and what you see is not real. What would you say if I told you that my voice was generated by an AI model?",
        segments=segments,
    )

    result = fraud_engine.analyze(speech)
    assert result.level == "LOW"
    assert len(result.requested_actions) == 0
    assert len(result.categories) == 0


def test_4_news_report_downgrade(fraud_engine):
    """
    Test Case 4: News report discussing a scam -> Downgrade applied.
    """
    segments = [
        SpeechSegment(
            start_s=0.0,
            end_s=5.0,
            text="In this news report, police warn that scammers try to make victims wire money immediately.",
        ),
    ]
    speech = SpeechResult(
        available=True,
        model="faster-whisper-base-int8",
        status="completed",
        language="en",
        duration_s=5.0,
        text="In this news report, police warn that scammers try to make victims wire money immediately.",
        segments=segments,
    )

    result = fraud_engine.analyze(speech)
    assert result.news_context_downgrade is True
    # Downgraded from HIGH -> MEDIUM
    assert result.level == "MEDIUM"


def test_5_direct_request_can_you_send_me_money(fraud_engine):
    """
    Test Case 5: Direct request 'Can you send me money?' -> SEND_MONEY action.
    """
    segments = [
        SpeechSegment(
            start_s=0.0,
            end_s=3.0,
            text="Can you send me money for the concert tickets?",
        ),
    ]
    speech = SpeechResult(
        available=True,
        model="faster-whisper-base-int8",
        status="completed",
        language="en",
        duration_s=3.0,
        text="Can you send me money for the concert tickets?",
        segments=segments,
    )

    result = fraud_engine.analyze(speech)
    assert any(act.action == "SEND_MONEY" for act in result.requested_actions)
    # Without urgency/authority/threat, casual request is MEDIUM (or LOW)
    assert result.level == "MEDIUM"


def test_6_direct_request_send_rupees_immediately(fraud_engine):
    """
    Test Case 6: 'Send me ₹50,000 immediately.' -> SEND_MONEY + URGENCY -> HIGH.
    """
    segments = [
        SpeechSegment(
            start_s=0.0,
            end_s=3.0,
            text="Send me ₹50,000 immediately or your account will be blocked.",
        ),
    ]
    speech = SpeechResult(
        available=True,
        model="faster-whisper-base-int8",
        status="completed",
        language="en",
        duration_s=3.0,
        text="Send me ₹50,000 immediately or your account will be blocked.",
        segments=segments,
    )

    result = fraud_engine.analyze(speech)
    assert result.level == "HIGH"
    assert any(act.action == "SEND_MONEY" for act in result.requested_actions)
    assert any(cat.category == "URGENCY" for cat in result.categories)


def test_7_ceo_transfer_rupees(fraud_engine):
    """
    Test Case 7: 'I am your CEO. I need you to transfer ₹50,000 immediately.' -> HIGH.
    """
    segments = [
        SpeechSegment(
            start_s=0.0,
            end_s=4.0,
            text="I am your CEO. I need you to transfer ₹50,000 immediately.",
        ),
    ]
    speech = SpeechResult(
        available=True,
        model="faster-whisper-base-int8",
        status="completed",
        language="en",
        duration_s=4.0,
        text="I am your CEO. I need you to transfer ₹50,000 immediately.",
        segments=segments,
    )

    result = fraud_engine.analyze(speech)
    assert result.level == "HIGH"
    assert any(cat.category == "AUTHORITY" for cat in result.categories)
    assert any(act.action == "TRANSFER_MONEY" for act in result.requested_actions)
    assert any(cat.category == "URGENCY" for cat in result.categories)


def test_8_send_money_and_secrecy(fraud_engine):
    """
    Test Case 8: 'I need you to send me money and don't tell anyone.' -> HIGH.
    """
    segments = [
        SpeechSegment(
            start_s=0.0,
            end_s=4.0,
            text="I need you to send me money and don't tell anyone.",
        ),
    ]
    speech = SpeechResult(
        available=True,
        model="faster-whisper-base-int8",
        status="completed",
        language="en",
        duration_s=4.0,
        text="I need you to send me money and don't tell anyone.",
        segments=segments,
    )

    result = fraud_engine.analyze(speech)
    assert result.level == "HIGH"
    assert any(act.action == "SEND_MONEY" for act in result.requested_actions)
    assert any(cat.category == "SECRECY" for cat in result.categories)


def test_9_otp_and_remote_access(fraud_engine):
    """
    Test Case 9: Direct OTP and AnyDesk installation demands -> HIGH.
    """
    speech_otp = SpeechResult(
        available=True,
        model="faster-whisper-base-int8",
        status="completed",
        language="en",
        duration_s=4.0,
        text="This is technical support. Please install AnyDesk and share your OTP verification code right now.",
        segments=[
            SpeechSegment(
                start_s=0.0,
                end_s=4.0,
                text="This is technical support. Please install AnyDesk and share your OTP verification code right now.",
            )
        ],
    )
    result = fraud_engine.analyze(speech_otp)
    assert result.level == "HIGH"
    assert any(act.action == "INSTALL_REMOTE_ACCESS" for act in result.requested_actions)
    assert any(act.action == "SHARE_OTP" for act in result.requested_actions)


def test_10_no_speech(fraud_engine):
    """
    Test Case 10: No speech available.
    """
    speech_empty = SpeechResult(
        available=False,
        model="faster-whisper-base-int8",
        status="not_available",
        language=None,
        duration_s=0.0,
        text="",
        segments=[],
    )
    result = fraud_engine.analyze(speech_empty)
    assert result.level == "NOT_ASSESSABLE"


def test_11_joke_send_me_money_bro(fraud_engine):
    """Jokes with emojis: 'send me money bro 😂' -> LOW."""
    speech = SpeechResult(
        available=True,
        model="faster-whisper-base-int8",
        status="completed",
        language="en",
        duration_s=3.0,
        text="send me money bro 😂",
        segments=[SpeechSegment(start_s=0.0, end_s=3.0, text="send me money bro 😂")],
    )
    res = fraud_engine.analyze(speech)
    assert res.level == "LOW"


def test_12_legitimate_conversation_debt(fraud_engine):
    """Legitimate conversation: 'Can you send me the money you owe me?' -> LOW."""
    speech = SpeechResult(
        available=True,
        model="faster-whisper-base-int8",
        status="completed",
        language="en",
        duration_s=3.0,
        text="Can you send me the money you owe me for lunch?",
        segments=[SpeechSegment(start_s=0.0, end_s=3.0, text="Can you send me the money you owe me for lunch?")],
    )
    res = fraud_engine.analyze(speech)
    assert res.level == "LOW"


def test_13_news_police_warning(fraud_engine):
    """News: 'Police warned people not to send money.' -> news downgrade / LOW."""
    speech = SpeechResult(
        available=True,
        model="faster-whisper-base-int8",
        status="completed",
        language="en",
        duration_s=4.0,
        text="Police warned people not to send money to unknown callers.",
        segments=[SpeechSegment(start_s=0.0, end_s=4.0, text="Police warned people not to send money to unknown callers.")],
    )
    res = fraud_engine.analyze(speech)
    assert res.news_context_downgrade is True or res.level == "LOW"


def test_14_educational_never_share_otp(fraud_engine):
    """Educational: 'Never share your OTP.' -> LOW, no SHARE_OTP action."""
    speech = SpeechResult(
        available=True,
        model="faster-whisper-base-int8",
        status="completed",
        language="en",
        duration_s=3.0,
        text="Never share your OTP with anyone.",
        segments=[SpeechSegment(start_s=0.0, end_s=3.0, text="Never share your OTP with anyone.")],
    )
    res = fraud_engine.analyze(speech)
    assert res.level == "LOW"
    assert not any(act.action == "SHARE_OTP" for act in res.requested_actions)


def test_15_scam_send_otp_immediately(fraud_engine):
    """Scam: 'Send me your OTP immediately.' -> HIGH."""
    speech = SpeechResult(
        available=True,
        model="faster-whisper-base-int8",
        status="completed",
        language="en",
        duration_s=3.0,
        text="Send me your OTP immediately right now.",
        segments=[SpeechSegment(start_s=0.0, end_s=3.0, text="Send me your OTP immediately right now.")],
    )
    res = fraud_engine.analyze(speech)
    assert res.level == "HIGH"
    assert any(act.action == "SHARE_OTP" for act in res.requested_actions)


def test_16_authority_manager_transfer_money_now(fraud_engine):
    """Authority: 'I am your manager. Transfer the money now.' -> HIGH."""
    speech = SpeechResult(
        available=True,
        model="faster-whisper-base-int8",
        status="completed",
        language="en",
        duration_s=4.0,
        text="I am your manager. Transfer the money now immediately.",
        segments=[SpeechSegment(start_s=0.0, end_s=4.0, text="I am your manager. Transfer the money now immediately.")],
    )
    res = fraud_engine.analyze(speech)
    assert res.level == "HIGH"
    assert any(act.action in ("TRANSFER_MONEY", "SEND_MONEY") for act in res.requested_actions)


def test_17_indirect_card_not_working_transfer(fraud_engine):
    """Indirect: 'My card isn't working. Can you make a small transfer?' -> detects TRANSFER_MONEY."""
    speech = SpeechResult(
        available=True,
        model="faster-whisper-base-int8",
        status="completed",
        language="en",
        duration_s=4.0,
        text="My card isn't working. Can you make a small transfer?",
        segments=[SpeechSegment(start_s=0.0, end_s=4.0, text="My card isn't working. Can you make a small transfer?")],
    )
    res = fraud_engine.analyze(speech)
    assert any(act.action == "TRANSFER_MONEY" for act in res.requested_actions)

