import pytest
from app.schemas.analysis import SpeechResult, SpeechSegment
from app.services.fraud_engine import FraudIntentEngine


@pytest.fixture
def fraud_engine():
    return FraudIntentEngine()


def test_1_high_fraud_ceo_scam(fraud_engine):
    """
    Test Case 1: High-risk CEO wire scam with urgency, secrecy, and payment request.
    """
    segments = [
        SpeechSegment(
            start_s=0.0,
            end_s=3.0,
            text="This is the CEO speaking. We have an urgent acquisition deal.",
        ),
        SpeechSegment(
            start_s=3.0,
            end_s=6.0,
            text="Transfer funds immediately to the new account number and keep this strictly confidential.",
        ),
    ]
    speech = SpeechResult(
        available=True,
        model="faster-whisper-base-int8",
        status="completed",
        language="en",
        duration_s=6.0,
        text="This is the CEO speaking. We have an urgent acquisition deal. Transfer funds immediately to the new account number and keep this strictly confidential.",
        segments=segments,
    )

    result = fraud_engine.analyze(speech)
    assert result.level == "HIGH"
    assert any(cat.category == "AUTHORITY" for cat in result.categories)
    assert any(cat.category == "URGENCY" for cat in result.categories)
    assert any(cat.category == "SECRECY" for cat in result.categories)
    assert any(cat.category == "PAYMENT_CREDENTIAL" for cat in result.categories)
    assert any(act.action == "TRANSFER_MONEY" for act in result.requested_actions)
    assert not result.news_context_downgrade


def test_2_medium_fraud_manager_payment(fraud_engine):
    """
    Test Case 2: Mention of authority and payments without aggressive pressure.
    """
    segments = [
        SpeechSegment(
            start_s=0.0,
            end_s=4.0,
            text="Hi team, speaking as the project manager, please review the upcoming invoice details.",
        ),
    ]
    speech = SpeechResult(
        available=True,
        model="faster-whisper-base-int8",
        status="completed",
        language="en",
        duration_s=4.0,
        text="Hi team, speaking as the project manager, please review the upcoming invoice details.",
        segments=segments,
    )

    result = fraud_engine.analyze(speech)
    assert result.level in ("MEDIUM", "LOW")
    assert any(cat.category == "AUTHORITY" for cat in result.categories)
    assert len(result.requested_actions) == 0


def test_3_harmless_ai_media(fraud_engine):
    """
    Test Case 3: Benign speech (e.g. Morgan Freeman AI clip).
    """
    segments = [
        SpeechSegment(
            start_s=0.0,
            end_s=4.0,
            text="I am not Morgan Freeman, and what you see is not real.",
        ),
        SpeechSegment(
            start_s=4.0,
            end_s=8.0,
            text="What would you say if I told you that my voice was generated by an AI model?",
        ),
    ]
    speech = SpeechResult(
        available=True,
        model="faster-whisper-base-int8",
        status="completed",
        language="en",
        duration_s=8.0,
        text="I am not Morgan Freeman, and what you see is not real. What would you say if I told you that my voice was generated by an AI model?",
        segments=segments,
    )

    result = fraud_engine.analyze(speech)
    assert result.level == "LOW"
    assert len(result.requested_actions) == 0
    assert len(result.categories) == 0


def test_4_news_report_downgrade(fraud_engine):
    """
    Test Case 4: News report discussing a scam -> Downgrade applied.
    """
    segments = [
        SpeechSegment(
            start_s=0.0,
            end_s=5.0,
            text="In this news report, police warn that scammers try to make victims wire money immediately.",
        ),
    ]
    speech = SpeechResult(
        available=True,
        model="faster-whisper-base-int8",
        status="completed",
        language="en",
        duration_s=5.0,
        text="In this news report, police warn that scammers try to make victims wire money immediately.",
        segments=segments,
    )

    result = fraud_engine.analyze(speech)
    assert result.news_context_downgrade is True
    # Should be downgraded from HIGH -> MEDIUM
    assert result.level == "MEDIUM"


def test_5_no_speech(fraud_engine):
    """
    Test Case 5: No speech or empty transcript.
    """
    speech_empty = SpeechResult(
        available=False,
        model="faster-whisper-base-int8",
        status="not_available",
        language=None,
        duration_s=0.0,
        text="",
        segments=[],
    )
    result = fraud_engine.analyze(speech_empty)
    assert result.level == "NOT_ASSESSABLE"
    assert len(result.categories) == 0
    assert len(result.requested_actions) == 0


def test_6_remote_access(fraud_engine):
    """
    Test Case 6: Tech support remote access scam.
    """
    segments = [
        SpeechSegment(
            start_s=0.0,
            end_s=4.0,
            text="This is technical support. Please install AnyDesk immediately to fix your account.",
        ),
    ]
    speech = SpeechResult(
        available=True,
        model="faster-whisper-base-int8",
        status="completed",
        language="en",
        duration_s=4.0,
        text="This is technical support. Please install AnyDesk immediately to fix your account.",
        segments=segments,
    )

    result = fraud_engine.analyze(speech)
    assert result.level == "HIGH"
    assert any(cat.category == "REMOTE_ACCESS_LINKS" for cat in result.categories)
    assert any(act.action == "INSTALL_REMOTE_ACCESS" for act in result.requested_actions)


def test_7_otp_request(fraud_engine):
    """
    Test Case 7: Bank security asking for OTP.
    """
    segments = [
        SpeechSegment(
            start_s=0.0,
            end_s=4.0,
            text="This is your bank security department. Please share your OTP verification code right now.",
        ),
    ]
    speech = SpeechResult(
        available=True,
        model="faster-whisper-base-int8",
        status="completed",
        language="en",
        duration_s=4.0,
        text="This is your bank security department. Please share your OTP verification code right now.",
        segments=segments,
    )

    result = fraud_engine.analyze(speech)
    assert result.level == "HIGH"
    assert any(act.action == "SHARE_OTP" for act in result.requested_actions)


def test_8_money_mention_without_request(fraud_engine):
    """
    Test Case 8: Money mentioned in general dialogue.
    """
    segments = [
        SpeechSegment(
            start_s=0.0,
            end_s=3.0,
            text="We discussed how bitcoin and crypto prices fluctuated yesterday.",
        ),
    ]
    speech = SpeechResult(
        available=True,
        model="faster-whisper-base-int8",
        status="completed",
        language="en",
        duration_s=3.0,
        text="We discussed how bitcoin and crypto prices fluctuated yesterday.",
        segments=segments,
    )

    result = fraud_engine.analyze(speech)
    assert result.level in ("LOW", "MEDIUM")
    assert len(result.requested_actions) == 0
